---
- name: Spring Petclinic Playbook
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    -  secrets.yml
  enviornment:
    AWS_DEFAULT_REGION: "{ { lookup('env', 'AWS_DEFAULT_REGION') | default('us-east-1', true) } }"
  tasks:
    -  include: tasks/create_stack.yml
       include: tasks/
       